// Generated by the ixaris microservices protocol buffer compiler. DO NOT EDIT!
// source: core_auth_sessions_api.proto

package com.ixaris.commons.microservices.test.mocks;

import javax.annotation.Generated;

import com.ixaris.commons.async.lib.Async;
import com.ixaris.commons.microservices.lib.common.Nil;
import com.ixaris.commons.microservices.lib.common.ServiceOperationHeader;
import com.ixaris.commons.microservices.lib.common.ServiceRootResource;
import com.ixaris.commons.microservices.lib.common.annotations.ServicePath;
import com.ixaris.commons.microservices.test.example.TestData.Context;

@Generated("com.ixaris.commons.microservices.scslcodegen")
public interface TestResource extends ServiceRootResource<Context> {
    
    String NAME = "test";
    
    @ServicePath
    NestedResource nested();
    
    public interface NestedResource {
        
        Async<Nil> operation(ServiceOperationHeader<Context> header);
        
        @ServicePath
        NestedIdResource nestedId(long nestedId);
        
        public interface NestedIdResource {
            
            Async<Nil> operation(ServiceOperationHeader<Context> header);
            
            @ServicePath
            MoreNestedResource moreNested();
            
            public interface MoreNestedResource {
                
                @ServicePath
                MoreNestedIdResource moreNestedId(long moreNestedId);
                
                public interface MoreNestedIdResource {
                    
                    Async<Nil> operation(ServiceOperationHeader<Context> header);
                    
                    Async<Nil> otherOperation(ServiceOperationHeader<Context> header);
                    
                }
                
            }
            
        }
        
    }
    
}
